[resources] # Required
runtime = "amopy0.3" # Required
timeout = 10         # Required, Options: 10, 30, 60
memory = 128         # Required

[profile] # Optional. Amo default profile
title = "é˜¿è«è¯´ä½ å¥½"
description = "å‘è‡ªå·±å‘é€ä¸€æ¡ Mixin Messenger æ¶ˆæ¯"

# arguments
# argument name: customized
# argument properties: label, type, value, hint, required, options
#   required properties: label, type, value
#   argument type: text, text-multiline, number, boolean, selection, mixin-assets
#   options format: [ ["label","value"], ... ]

[constants] # Optional, static arguments
# the value will be stored in server side

[constants.what]
label = "è¯´ä»€ä¹ˆ"
type = "text"
value = "ä½ å¥½ğŸ‘‹"
hint = ""
required = true


# [variables] # Optional, dynamic arguments
# the value be provided in request. (like webapp)
