[resources] # Required
runtime = "amopy0.3" # Required
timeout = 10         # Required, Options: 10, 30, 60
memory = 128         # Required

[profile] # Optional. Amo default profile
title = "çŒ«å¤´é¹°è¯´ä½ å¥½"
description = "é€šè¿‡çŒ«å¤´é¹°é€’ä¿¡å‘è‡ªå·±å‘é€ä¸€æ¡æ–‡æœ¬æ¶ˆæ¯ã€‚éœ€å…ˆæ·»åŠ çŒ«å¤´é¹°é€’ä¿¡æœºå™¨äºº(7000102034)ä¸ºå¥½å‹"

[arguments] # Optional, depends on script logic
# argument name: customized
# argument properties: label, type, value, hint, required, options
#   required properties: label, type, value
#   argument type: string, number, boolean, selection, mixin_assets
#   options format: [ ["label",value"], ... ]

[arguments.what]
label = "è¯´ä»€ä¹ˆ"
type = "string"
value = "ä½ å¥½ğŸ‘‹"
hint = ""
required = true
