arguments:
  what:
    hint: ""
    label: è¯´ä»€ä¹ˆ
    required: true
    type: string
    value: ä½ å¥½ğŸ‘‹
profile:
  description: é€šè¿‡çŒ«å¤´é¹°é€’ä¿¡å‘è‡ªå·±å‘é€ä¸€æ¡æ–‡æœ¬æ¶ˆæ¯ã€‚éœ€å…ˆæ·»åŠ çŒ«å¤´é¹°é€’ä¿¡æœºå™¨äºº(7000102034)ä¸ºå¥½å‹
  title: çŒ«å¤´é¹°è¯´ä½ å¥½
resources:
  memory: 128
  runtime: amopy0.3
  timeout: 10
